server.port=8080
spring.thymeleaf.cache=false
camunda.client.prefer-rest-over-grpc=false

# camunda.client.mode=${ZB_MODE}
# camunda.client.cloud.cluster-id=${ZB_CLUSTER}
# camunda.client.auth.client-id=${ZB_CLIENT}
# camunda.client.auth.client-secret=${ZB_SECRET}
# camunda.client.cloud.region=${ZB_REGION}

camunda.client.cloud.cluster-id=3a04edcc-94a3-4a93-9148-d2e7791ef583
camunda.client.auth.client-id=A.kmCM.C~Y9iiH43Ekvn7H2XtXAJcXEk
camunda.client.auth.client-secret=kS_o9egQSufE0h_X70LPwEk1Oh.7MgWBt3sjZ9X9.W09XTUzDU0~-O3JuyL82b6o
camunda.client.cloud.region=fra-1


logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR
