server.port=8080
spring.thymeleaf.cache=false
camunda.client.prefer-rest-over-grpc=false

# camunda.client.mode=${ZB_MODE}
# camunda.client.cloud.cluster-id=${ZB_CLUSTER}
# camunda.client.auth.client-id=${ZB_CLIENT}
# camunda.client.auth.client-secret=${ZB_SECRET}
# camunda.client.cloud.region=${ZB_REGION}

camunda.client.cloud.cluster-id=98230c11-3e6c-42f5-8e66-07928c4229b8
camunda.client.auth.client-id=ltwJt9mnJ5L4LQ_pNY_ok-Mrmm5ZGgXg
camunda.client.auth.client-secret=iO_98rmtktOHI3wy0GHaw97BV55YKz7.8GIN.gJRcc.r~aeMpqIqcGLqg2lgjGEU
camunda.client.cloud.region=fra-1


logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR
